// Exports one row per (case, department) pairing with every timestamp we have -- the raw
// database values plus what the audit log independently shows -- so Brenda can review them
// side by side and spot-check/correct anything that looks wrong. Everything before this app's
// June 2026 launch was bulk-imported from the prior system and is flagged separately, since
// that data was never generated by real step-by-step app usage the way everything after is.
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const LAUNCH_DATE = '2026-06-01T00:00:00.000Z'

// Same phrasings department-performance parses -- keep both in sync if the audit log wording
// in CaseDetail.jsx / SubmitForm.jsx / send-confirmation-email ever changes.
const ASSIGNED_TO_RE = /^Assigned to (.+)$/
const AUTO_ASSIGNED_RE = /^Auto-assigned to (.+?) based on issue type/
const REFERRED_TO_RE = /^Referred from .+ to (.+)$/
const DEPT_STATUS_RE = /^(.+?) status (?:changed|updated) from ".*?" to "(.+?)"/

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  const serviceRoleKey = Deno.env.get('SERVICE_ROLE_KEY')!
  const supabaseUrl = 'https://sdibtkmmcegthmytmzvy.supabase.co'
  const authHeaders = { apikey: serviceRoleKey, Authorization: `Bearer ${serviceRoleKey}` }

  const [deptRes, statusRes, cdRes] = await Promise.all([
    fetch(`${supabaseUrl}/rest/v1/departments?select=id,name`, { headers: authHeaders }),
    fetch(`${supabaseUrl}/rest/v1/statuses?select=name,is_closing`, { headers: authHeaders }),
    fetch(
      `${supabaseUrl}/rest/v1/case_departments?select=case_id,department_id,created_at,closed_date,statuses(name,is_closing),cases(case_number,date_submitted,issue_types(name))&order=case_id`,
      { headers: authHeaders }
    ),
  ])

  const departments: { id: number; name: string }[] = await deptRes.json()
  const statuses: { name: string; is_closing: boolean }[] = await statusRes.json()
  const rows: any[] = await cdRes.json()

  const deptNameToId = new Map(departments.map(d => [d.name.toLowerCase(), d.id]))
  const closingStatusNames = new Set(statuses.filter(s => s.is_closing).map(s => s.name.toLowerCase()))

  // Paginate -- PostgREST caps unpaginated responses at 1000 rows.
  const allCaseIds = [...new Set(rows.map(r => r.case_id))]
  const auditRows: { case_id: number; action: string; created_at: string }[] = []
  const PAGE_SIZE = 1000
  for (let offset = 0; ; offset += PAGE_SIZE) {
    const auditRes = await fetch(
      `${supabaseUrl}/rest/v1/case_audit_log?select=case_id,action,created_at&case_id=in.(${allCaseIds.join(',')})&order=created_at.asc&offset=${offset}&limit=${PAGE_SIZE}`,
      { headers: authHeaders }
    )
    const page = await auditRes.json()
    auditRows.push(...page)
    if (page.length < PAGE_SIZE) break
  }

  const assignedAtAudit = new Map<string, string>()
  const closedAtAudit = new Map<string, string>()

  for (const log of auditRows || []) {
    const key = (deptId: number) => `${log.case_id}:${deptId}`

    const assignedMatch = log.action.match(ASSIGNED_TO_RE) || log.action.match(AUTO_ASSIGNED_RE) || log.action.match(REFERRED_TO_RE)
    if (assignedMatch) {
      const deptId = deptNameToId.get(assignedMatch[1].trim().toLowerCase())
      if (deptId) {
        const k = key(deptId)
        if (!assignedAtAudit.has(k)) assignedAtAudit.set(k, log.created_at)
      }
    }

    const statusMatch = log.action.match(DEPT_STATUS_RE)
    if (statusMatch) {
      const deptId = deptNameToId.get(statusMatch[1].trim().toLowerCase())
      const newStatusName = statusMatch[2].trim().toLowerCase()
      if (deptId && closingStatusNames.has(newStatusName)) {
        closedAtAudit.set(key(deptId), log.created_at)
      }
    }
  }

  function daysBetween(startIso: string, endIso: string): number {
    return Math.round((new Date(endIso).getTime() - new Date(startIso).getTime()) / (1000 * 60 * 60 * 24))
  }

  // A negative day count means the "later" timestamp is chronologically before the "earlier"
  // one -- impossible for anything the app itself wrote, but it shows up on bulk-imported rows
  // whose timestamps were never in real lifecycle order. Null the day count out rather than
  // display a nonsense negative number, and say so plainly via *_dates_consistent.
  function daysBetweenIfConsistent(startIso: string | null, endIso: string | null): { days: number | null; consistent: boolean | null } {
    if (!startIso || !endIso) return { days: null, consistent: null }
    const days = daysBetween(startIso, endIso)
    return days < 0 ? { days: null, consistent: false } : { days, consistent: true }
  }

  const departmentsOnCase = new Map<number, number>()
  rows.forEach(r => departmentsOnCase.set(r.case_id, (departmentsOnCase.get(r.case_id) || 0) + 1))

  const exportRows = rows.map(r => {
    const k = `${r.case_id}:${r.department_id}`
    const dateSubmitted = r.cases?.date_submitted
    const assignedAtDb = r.created_at
    const closedAtDb = r.closed_date
    const auditAssigned = assignedAtAudit.get(k) || null
    const auditClosed = closedAtAudit.get(k) || null

    const submissionToAssignment = daysBetweenIfConsistent(dateSubmitted, assignedAtDb)
    const assignmentToCloseDb = daysBetweenIfConsistent(assignedAtDb, closedAtDb)
    const assignmentToCloseAudit = daysBetweenIfConsistent(auditAssigned || assignedAtDb, auditClosed)

    return {
      case_number: r.cases?.case_number,
      departments_on_this_case: departmentsOnCase.get(r.case_id),
      issue_type: r.cases?.issue_types?.name || '',
      department: departments.find(d => d.id === r.department_id)?.name || '',
      date_submitted: dateSubmitted,
      is_bulk_upload: dateSubmitted ? dateSubmitted < LAUNCH_DATE : null,
      current_status: r.statuses?.name || '',
      is_closing: Boolean(r.statuses?.is_closing),
      assigned_at_db: assignedAtDb,
      assigned_at_audit_log: auditAssigned,
      closed_at_db: closedAtDb,
      closed_at_audit_log: auditClosed,
      days_from_submission_to_assignment: submissionToAssignment.days,
      submission_to_assignment_dates_consistent: submissionToAssignment.consistent,
      days_from_assignment_to_close_db: assignmentToCloseDb.days,
      assignment_to_close_db_dates_consistent: assignmentToCloseDb.consistent,
      days_from_assignment_to_close_audit: assignmentToCloseAudit.days,
      assignment_to_close_audit_dates_consistent: assignmentToCloseAudit.consistent,
    }
  })

  return new Response(JSON.stringify(exportRows), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
})
